/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "tassadar_constants.h"



const tassadarConstants g_tassadar_constants;

tassadarConstants::tassadarConstants() {
}



