/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef tassadar_CONSTANTS_H
#define tassadar_CONSTANTS_H

#include "tassadar_types.h"



class tassadarConstants {
 public:
  tassadarConstants();

};

extern const tassadarConstants g_tassadar_constants;



#endif
